# -*- coding: utf-8 -*-
"""CIE 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x_-0uNxRYvAjMewFQoBU_HYcGOqrkW4r
"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
import tensorflow as tf
from tensorflow.datasets import mnist
from tensorflow.models import Sequential
from tensorflow.layers import Dense, Flatten
from tensorflow.callbacks import TensorBoard
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
model = Sequential([Flatten(input_shape=(28, 28)),Dense(128, activation= 'relu'),Dense(10, activation='softmax')])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
tensorboard_callback= TensorBoard(log_dir='./logs')
model.fit(x_train, y_train, epochs=5, batch_size=32, validation_data=(x_test,y_test), callbacks=[tensorboard_callback])
test_loss, test_acc = model.evaluate(x_test, y_test)
print(f'Test accuracy:', test_acc)
# %tensorboard --logdir=./logs/fit

